/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.studylist.views;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Ana
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    private ArrayList<String> integrantes = new ArrayList<>(List.of(
            "236697 - Ana Julia Paifer",
            "236651 - Sarah Ferreira Dias de Oliveira",
            "236681 - Brenda Miranda Rodrigues",
            "236638 - Milene Leite Micheloti",
            "236754 - Lauren Giulia Marcondes"
    ));

    public TelaInicial() {
        initComponents();
        try {
            scaledImage();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar imagem: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }

        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = 0; i <= 100; i++) {

                    switch (i) {
                        case 1:
                            jbAna.setText(integrantes.get(0));
                            txtLoading.setText("Carregando.");
                            break;
                        case 19:
                            jbLauren.setText(integrantes.get(2));
                            txtLoading.setText("Carregando..");
                            break;
                        case 29:
                            jbMilene.setText(integrantes.get(3));
                            txtLoading.setText("Carregando...");
                            break;
                        case 38:
                            jbBrenda.setText(integrantes.get(1));
                            txtLoading.setText("Carregando....");
                            break;
                        case 47:
                            jbSarah.setText(integrantes.get(4));
                            txtLoading.setText("Carregando.....");
                            break;
                        case 70:
                            txtLoading.setText("CARREGAMENTO CONCLUIDO");
                            break;
                        case 90:
                           encerramento();
                            break;
                    }

                    try {
                        Thread.sleep(60);
                        loading.setValue(i);
                    } catch (InterruptedException ex) {
                        ex.printStackTrace();
                    }
                }
            }
        }).start();
    }
    
    private void encerramento(){
        OptionsView op = new OptionsView();
        op.setVisible(true);
        this.setVisible(false);
    }

    public void scaledImage() throws IOException {
        BufferedImage originalImage1 = ImageIO.read(new File("src/main/java/org/studylist/imgs/back.png"));

        Image imgScale = originalImage1.getScaledInstance(img.getWidth(), img.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon sclimg1 = new ImageIcon(imgScale);
        img.setIcon(sclimg1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtLoading = new javax.swing.JLabel();
        jbSarah = new javax.swing.JLabel();
        jbBrenda = new javax.swing.JLabel();
        jbMilene = new javax.swing.JLabel();
        jbLauren = new javax.swing.JLabel();
        jbAna = new javax.swing.JLabel();
        loading = new javax.swing.JProgressBar();
        img = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        txtLoading.setBackground(new java.awt.Color(0, 0, 0));
        txtLoading.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        txtLoading.setForeground(new java.awt.Color(153, 51, 255));
        txtLoading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(txtLoading);
        txtLoading.setBounds(200, 460, 440, 40);

        jbSarah.setBackground(new java.awt.Color(255, 255, 255));
        jbSarah.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jbSarah.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jbSarah);
        jbSarah.setBounds(20, 400, 490, 30);

        jbBrenda.setBackground(new java.awt.Color(255, 255, 255));
        jbBrenda.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jbBrenda.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jbBrenda);
        jbBrenda.setBounds(20, 370, 490, 30);

        jbMilene.setBackground(new java.awt.Color(255, 255, 255));
        jbMilene.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jbMilene.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jbMilene);
        jbMilene.setBounds(20, 340, 490, 30);

        jbLauren.setBackground(new java.awt.Color(255, 255, 255));
        jbLauren.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jbLauren.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jbLauren);
        jbLauren.setBounds(20, 310, 490, 30);

        jbAna.setBackground(new java.awt.Color(255, 255, 255));
        jbAna.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jbAna.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jbAna);
        jbAna.setBounds(20, 280, 490, 30);

        loading.setBackground(new java.awt.Color(204, 153, 255));
        loading.setForeground(new java.awt.Color(153, 51, 255));
        getContentPane().add(loading);
        loading.setBounds(20, 500, 800, 50);
        getContentPane().add(img);
        img.setBounds(0, 0, 850, 590);

        setSize(new java.awt.Dimension(845, 599));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel img;
    private javax.swing.JLabel jbAna;
    private javax.swing.JLabel jbBrenda;
    private javax.swing.JLabel jbLauren;
    private javax.swing.JLabel jbMilene;
    private javax.swing.JLabel jbSarah;
    private javax.swing.JProgressBar loading;
    private javax.swing.JLabel txtLoading;
    // End of variables declaration//GEN-END:variables
}
